### ISSUE TITLE
function collect_all_ratios not work when there's only on symbol[BUG]

### ISSUE THREAD

**Issue by alberthaoh** [JerBouma/FinanceToolkit#101]
With financetoolkit-1.8.0 if we doing following
companies = ft.Toolkit(["AAPL"], api_key=API_KEY, start_date="1990-12-31", quarterly=True)

all_ratios_trail = companies.ratios.collect_all_ratios(growth=True,
                                                 diluted = False, trailing = 1, lag = 1, )
it'll say 'There is an index name missing in the provided financial statements. This is "Cannot interpret 'AAPL' as period". This is required for the function (collect_all_ratios) to run. Please fill this column to be able to calculate the ratios.'

I think this is because one/some dataframes when created with only one symbol, the symbol will not in the multiindex. Little bit hard for me to debug this, would be great if you could fix it.

thanks a lot!

**Comment by JerBouma** [comment]
Hi! Please use an additional ticker for now. I'll fix it next week!

**Comment by JerBouma** [comment]
This issue has been resolved in the newest release, please update with `pip install financetoolkit -U`.

<img width="1251" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/5ae04404-6f1c-4204-9b8b-7842065cd40d">

**Comment by alberthaoh** [comment]
great work!🚀🚀🚀
