### ISSUE TITLE
[Bug] Formula for custom metrics that have '(' or ')'

### ISSUE THREAD

**Issue by nguyenkien1402** [JerBouma/FinanceToolkit#108]
**What's the feature that should be improved?**
The underlying code for collect_custom_metric splits the formula based on the following operators.
for operator in [
                "+",
                "-",
                "*",
                "/",
                "**",
                "%",
                "//",
                "<",
                ">",
                "==",
                "!=",
                ">=",
                "<=",
                "(",
                ")",
            ]:

This causes the issue when passing the metric with '( )' such as:
 'Return on Assets (ROA)',
 'Return on Capital Employed (ROCE)',
 'Return on Equity (ROE)',
 'Return on Invested Capital (ROIC)',
'Earnings per Share (EPS)',
etc
The split will treat '( )' as a formula, hence, resulting in Return on Assets (ROA) becoming Return on Assets, hence causing the error: "Column Return on Assets not found in total_financials and is not a number".

**Comment by JerBouma** [comment]
This issue has been fixed in v1.8.2, please upgrade.

<img width="1246" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/f8673044-26dc-40e8-b902-82ce7435e3f2">
