### ISSUE TITLE
currency converting issue in get_balance_sheet_statement [BUG]

### ISSUE THREAD

**Issue by alberthaoh** [JerBouma/FinanceToolkit#110]
Hi ,
When calling get_balance_sheet_statement(), when the setting is quaterly. there are some error
companies = ft.Toolkit(["TSM"], api_key=API_KEY, start_date="1990-12-31", quarterly=True)
companies.get_balance_sheet_statement()

IndexingError: Too many indexers

It's working when Quaterly=False.

Would be great if it could be fixed😊. Thanks a lot!

**Comment by JerBouma** [comment]
Hi! This is an issue only if you provide one ticker, you can resolve this by adding an additional ticker. Alternatively, set `convert_currency=False`. I'll fix this issue this week.

**Comment by JerBouma** [comment]
This issue has been fixed in v1.8.2, please upgrade.

<img width="1249" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/e11fe572-ffff-4b7a-bdd1-dbd0e3c3a5d3">
