### ISSUE TITLE
error while calling the functions

### ISSUE THREAD

**Issue by shivansh2310** [JerBouma/FinanceToolkit#112]
I was trying to follow the provided notebook to learn how this library works, but whenever I call the functions I get this error can anyone help? I don't understand what the issue.

`AttributeError: 'DataFrame' object has no attribute '_constructor_from_mgr`

I am using Google Colab with Free API_KEY

**Comment by JerBouma** [comment]
Hi! Can you provide me with what version of the Finance Toolkit you are using and what command won't work? This seems to be a Colab specific issue but I cannot test it without this information.

**Comment by shivansh2310** [comment]
Hi sir thanks for replying, It was an Colab specific issue, I Restarted the kernel and everything is working fine.

**Comment by JerBouma** [comment]
That's good to hear! Let me know if you run into any other issues.
