### ISSUE TITLE
option chain data

### ISSUE THREAD

**Issue by andrewcz** [JerBouma/FinanceToolkit#113]
Is there an easy way to get option chain data for a ticker
cheers @JerBouma

**Comment by JerBouma** [comment]
Hi! Please have a look here: https://www.jeroenbouma.com/projects/financetoolkit/docs/options#get_option_chains. I did notice that the Yahoo Finance API can be a bit unstable so if the code doesn't work, let me know. I'll introduce a fix today.

**Comment by andrewcz** [comment]
thank you sir!
