### ISSUE TITLE
Error in company.ratios Function

### ISSUE THREAD

**Issue by kurucan** [JerBouma/FinanceToolkit#116]
I've encountered an issue while using the Toolkit's company.ratios function. Specifically, the problem arises when I attempt to fetch ratios for the ticker 'MLCOR.PA'.

Here's a brief overview of my code:

from toolkit import Toolkit

_API_KEY = 'your_api_key_here'  # Replace with your actual API key
company = Toolkit(tickers=['MLCOR.PA'], api_key=API_KEY, sleep_timer=True, benchmark_ticker=None, progress_bar=False, start_date="2004-01-01")
company.ratios.collect_profitability_ratios()_

Upon running this code, I encounter the following error:

_--------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /opt/envs/venv-python3.11/lib/python3.11/site-packages/pandas/core/indexes/base.py:3802, in Index.get_loc(self, key)
   3801 try:
-> 3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:

File index.pyx:153, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:161, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/index_class_helper.pxi:70, in pandas._libs.index.Int64Engine._check_type()

KeyError: 'Reported Currency'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[19], line 2
      1 company = Toolkit(tickers=['MLCOR.PA'], api_key=API_KEY, sleep_timer=True, benchmark_ticker=None, progress_bar=False, start_date="2004-01-01")
----> 2 company.ratios.collect_profitability_ratios()

File /opt/envs/venv-python3.11/lib/python3.11/site-packages/financetoolkit/toolkit_controller.py:528, in Toolkit.ratios(self)
    526 for statement in empty_data_iterator:
    527     if statement == "Balance Sheet Statement":
--> 528         self.get_balance_sheet_statement(progress_bar=False)
    529     if statement == "Income Statement":
    530         self.get_income_statement(progress_bar=False)

File /opt/envs/venv-python3.11/lib/python3.11/site-packages/financetoolkit/toolkit_controller.py:2828, in Toolkit.get_balance_sheet_statement(self, overwrite, rounding, growth, lag, trailing, progress_bar)
   2820     self._balance_sheet_statement_growth = _calculate_growth(
   2821         balance_sheet_statement,
   2822         lag=lag,
   2823         rounding=rounding if rounding else self._rounding,
   2824         axis="columns",
   2825     )
   2827 if convert_currency:
-> 2828     self.get_exchange_rates(
   2829         period="quarterly" if self._quarterly else "yearly",
   2830         progress_bar=progress_bar
   2831         if progress_bar is not None
   2832         else self._progress_bar,
   2833     )
   2835     balance_sheet_statement = helpers.convert_currencies(
   2836         financial_statement_data=balance_sheet_statement,
   2837         financial_statement_currencies=self._statement_currencies,
   (...)
   2841         financial_statement_name="balance sheet statement",
   2842     )
   2844 balance_sheet_statement = balance_sheet_statement.round(
   2845     rounding if rounding else self._rounding
   2846 )

File /opt/envs/venv-python3.11/lib/python3.11/site-packages/financetoolkit/toolkit_controller.py:2560, in Toolkit.get_exchange_rates(self, period, return_column, fill_nan, overwrite, rounding, show_ticker_seperation, progress_bar)
   2552     if self._statistics_statement.empty:
   2553         self.get_statistics_statement(
   2554             progress_bar=progress_bar
   2555             if progress_bar is not None
   2556             else self._progress_bar
   2557         )
   2559     self._statement_currencies, self._currencies = helpers.determine_currencies(
-> 2560         statement_currencies=self._statistics_statement.xs(
   2561             "Reported Currency", axis=0, level=1
   2562         ),
   2563         historical_currencies=self._historical_statistics.loc["Currency"],
   2564     )
   2566 if self._daily_exchange_rate_data.empty or overwrite:
   2567     self._daily_exchange_rate_data, _ = _get_historical_data(
   2568         tickers=self._currencies,
   2569         api_key=self._api_key,
   (...)
   2584         tqdm_message="Obtaining exchange data",
   2585     )

File /opt/envs/venv-python3.11/lib/python3.11/site-packages/pandas/core/generic.py:4268, in NDFrame.xs(self, key, axis, level, drop_level)
   4266 if not isinstance(labels, MultiIndex):
   4267     raise TypeError("Index must be a MultiIndex")
-> 4268 loc, new_ax = labels.get_loc_level(key, level=level, drop_level=drop_level)
   4270 # create the tuple of the indexer
   4271 _indexer = [slice(None)] * self.ndim

File /opt/envs/venv-python3.11/lib/python3.11/site-packages/pandas/core/indexes/multi.py:3150, in MultiIndex.get_loc_level(self, key, level, drop_level)
   3147 else:
   3148     level = [self._get_level_number(lev) for lev in level]
-> 3150 loc, mi = self._get_loc_level(key, level=level)
   3151 if not drop_level:
   3152     if lib.is_integer(loc):
   3153         # Slice index must be an integer or None

File /opt/envs/venv-python3.11/lib/python3.11/site-packages/pandas/core/indexes/multi.py:3290, in MultiIndex._get_loc_level(self, key, level)
   3288         return indexer, maybe_mi_droplevels(indexer, ilevels)
   3289 else:
-> 3290     indexer = self._get_level_indexer(key, level=level)
   3291     if (
   3292         isinstance(key, str)
   3293         and self.levels[level]._supports_partial_string_indexing
   3294     ):
   3295         # check to see if we did an exact lookup vs sliced
   3296         check = self.levels[level].get_loc(key)

File /opt/envs/venv-python3.11/lib/python3.11/site-packages/pandas/core/indexes/multi.py:3391, in MultiIndex._get_level_indexer(self, key, level, indexer)
   3388         return slice(i, j, step)
   3390 else:
-> 3391     idx = self._get_loc_single_level_index(level_index, key)
   3393     if level > 0 or self._lexsort_depth == 0:
   3394         # Desired level is not sorted
   3395         if isinstance(idx, slice):
   3396             # test_get_loc_partial_timestamp_multiindex

File /opt/envs/venv-python3.11/lib/python3.11/site-packages/pandas/core/indexes/multi.py:2980, in MultiIndex._get_loc_single_level_index(self, level_index, key)
   2978     return -1
   2979 else:
-> 2980     return level_index.get_loc(key)

File /opt/envs/venv-python3.11/lib/python3.11/site-packages/pandas/core/indexes/base.py:3809, in Index.get_loc(self, key)
   3804     if isinstance(casted_key, slice) or (
   3805         isinstance(casted_key, abc.Iterable)
   3806         and any(isinstance(x, slice) for x in casted_key)
   3807     ):
   3808         raise InvalidIndexError(key)
-> 3809     raise KeyError(key) from err
   3810 except TypeError:
   3811     # If we have a listlike key, _check_indexing_error will raise
   3812     #  InvalidIndexError. Otherwise we fall through and re-raise
   3813     #  the TypeError.
   3814     self._check_indexing_error(key)

KeyError: 'Reported Currency'_

**Comment by JerBouma** [comment]
There is no data for this ticker which is why you get the error: https://site.financialmodelingprep.com/financial-statements/MLCOR.PA. Even Bloomberg has no data: https://www.bloomberg.com/quote/MLCOR:FP

I believe you are looking at a Private company given no provider has any market or fundamental data.
