### ISSUE TITLE
Growth, value, quality stocks info ?

### ISSUE THREAD

**Issue by kurucan** [JerBouma/FinanceToolkit#120]
Does FinancialToolkit offer a feature to categorize stocks into growth, value, quality or momentum segments?

**Comment by JerBouma** [comment]
Hi!

This type of categorization is often dependent on your definition of each category. I do not classify stocks accordingly.

What you can do is have a look at the Fama and French model, perform a regression and determine the sensitivities of each stock to these factors. See: https://www.jeroenbouma.com/projects/financetoolkit/docs/performance#get_fama_and_french_model

This should give similar results to categorisations done elsewhere.
