### ISSUE TITLE
ValueError: Value is too big!

### ISSUE THREAD

**Issue by sword134** [JerBouma/FinanceToolkit#123]
Running the following code for the ticker list will result in an ValueError: Value is too big!

```
symbols = ['ACTDU', 'ACTG', 'ACVA', 'ADAL', 'ADBE', 'ADC', 'ADEA', 'ADEX-UN', 'ADEX-WT', 'ADEXU', 'ADI', 'ADM', 'ADMA', 'ADP', 'ADPT', 'ADS', 'ADSK', 'ADT', 'ADTN', 'ADUS', 'ADV', 'AEE', 'AEGN', 'AEHR', 'AEIS', 'AEL', 'AEL-PA', 'AEL-PB', 'AEO', 'AEP', 'AEPPL', 'AEPPZ', 'AERI', 'AES', 'AESC', 'AEVA-WT', 'AFBA', 'AFFS', 'AFG', 'AFGB', 'AFGC', 'AFGD', 'AFGE', 'AFIN', 'AFINO', 'AFINP', 'AFL', 'AFRM', 'AFSIA', 'AFSIB', 'AFSIC', 'AFSIM', 'AFSIP', 'AGAC-UN', 'AGAC-WT', 'AGACU', 'AGC', 'AGCB', 'AGCO', 'AGCUU', 'AGCWW', 'AGIO', 'AGL', 'AGLY', 'AGM', 'AGM-A', 'AGM-PC', 'AGM-PD', 'AGM-PE', 'AGM-PF', 'AGMGP', 'AGNC', 'AGNCL', 'AGNCM', 'AGNCN', 'AGNCO', 'AGNCP', 'AGR', 'AGRIP', 'AGS', 'AGTI', 'AGX', 'AGXXF', 'AGYS', 'AHCO', 'AHH', 'AHH-PA', 'AHT-PD', 'AHT-PF', 'AHT-PG', 'AHT-PH', 'AHT-PI', 'AI', 'AIABF', 'AIC', 'AIG', 'AIG-PA', 'AILIH', 'AILIM', 'AILIN', 'AILIO', 'AILIP', 'AILLI', 'AILLN', 'AILLP', 'AIMC', 'AIN', 'AINV', 'AIO', 'AIR', 'AIRC', 'AIRS', 'AIT', 'AIV', 'AIZ', 'AIZN', 'AJAX', 'AJAX-UN', 'AJAX-WT', 'AJG', 'AJRD', 'AJXA', 'AKAM', 'AKR', 'AKRO', 'AKUS', 'AL', 'ALB', 'ALBO', 'ALE', 'ALEC', 'ALEX', 'ALG', 'ALGM', 'ALGN', 'ALGT', 'ALHC', 'ALK', 'ALKT', 'ALL', 'ALL-PB', 'ALL-PG', 'ALL-PH', 'ALL-PI', 'ALLO', 'ALLY', 'ALMFF', 'ALNT', 'ALNY', 'ALP-PQ', 'ALPIB', 'ALPN', 'ALPVN', 'ALRM', 'ALRS', 'ALSN', 'ALT', 'ALTA', 'ALTG', 'ALTG-PA', 'ALTI', 'ALTR', 'ALX', 'ALXN']
start_date = datetime(2008, 1, 1)
companies = Toolkit(symbols, api_key=API_KEY, quarterly=True, start_date=start_date.strftime('%Y-%m-%d'), sleep_timer=True, progress_bar=True, remove_invalid_tickers=False)

df_ratios = companies.ratios.collect_all_ratios()

```

**Comment by JerBouma** [comment]
Please provide the full error code. It shouldn't fail with these amounts of tickers!

**Comment by sword134** [comment]
Ok so its because im passing too many tickers? This is just a snapshot of the symbols

**Comment by sword134** [comment]
> Please provide the full error code. It shouldn't fail with these amounts of tickers!

Even though I reduce the number of tickers to the following:

symbols_temp= ['A', 'AA', 'AAC', 'AAGH', 'AAIN', 'AAL', 'AAN', 'AAOI', 'AAON', 'AAP', 'AAPL', 'AAT', 'AAWW', 'AB', 'ABBV', 'ABC', 'ABCB', 'ABG', 'ABL', 'ABM', 'ABMD', 'ABML', 'ABNB', 'ABR', 'ABR-PA', 'ABR-PB', 'ABR-PC', 'ABSI', 'ABT', 'ABTX', 'ABUS', 'AC', 'ACA', 'ACAD', 'ACAN', 'ACBI', 'ACC', 'ACCD', 'ACCO', 'ACDC', 'ACEL', 'ACHC', 'ACHR', 'ACI', 'ACIC', 'ACIC-UN', 'ACIC-WT', 'ACICU', 'ACII', 'ACII-UN', 'ACII-WT', 'ACIW', 'ACLS', 'ACLX', 'ACM', 'ACMR', 'ACNB', 'ACND', 'ACND-UN', 'ACND-WT', 'ACRE', 'ACTC', 'ACTCU', 'ACTCW', 'ACTD', 'ACTDU', 'ACTG', 'ACVA', 'ADAL', 'ADBE', 'ADC', 'ADEA', 'ADEX-UN', 'ADEX-WT', 'ADEXU', 'ADI', 'ADM', 'ADMA', 'ADP', 'ADPT', 'ADS', 'ADSK', 'ADT', 'ADTN', 'ADUS', 'ADV', 'AEE', 'AEGN', 'AEHR', 'AEIS', 'AEL', 'AEL-PA', 'AEL-PB', 'AEO', 'AEP', 'AEPPL', 'AEPPZ', 'AERI', 'AES', 'AESC']

It will throw alot of ValueError: 0 is not in range errors using the below code:
```

companies = Toolkit(symbols_temp, api_key=API_KEY, quarterly=True, start_date=start_date.strftime('%Y-%m-%d'), sleep_timer=True, progress_bar=True, remove_invalid_tickers=True)

        custom_ratios = {
            "WC / Net Income as %": "(Working Capital / Net Income) * 100",
            "Working Capital Ratio": "Working Capital / Revenue",
        }

        df_ratios = companies.ratios.collect_all_ratios()
        df_custom = companies.ratios.collect_custom_ratios(custom_ratios_dict=custom_ratios)
        df_stats = companies.get_statistics_statement()

        df_stock_price = companies.get_historical_data(fill_nan=False, period="daily")

        df_ratios_growth_TTM = companies.ratios.collect_all_ratios(growth=True, lag=[1, 2, 3, 4, 5], trailing=4)
```

**Comment by JerBouma** [comment]
I tried to reproduce this error but unfortunately I can't, it works fine for me. Did you upgrade to the latest release?

<img width="1154" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/af34d774-d840-42ed-a3c1-bd1fbc46fcd8">

**Comment by JerBouma** [comment]
For the second piece of code, not setting `remove_invalid_tickers` to `False` can sometimes lead to issues as seen here. This can be corrected by changing this as seen here:

<img width="1011" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/b5f0d38e-8769-4a79-8bd0-6059ce06b8a3">
