### ISSUE TITLE
[BUG] IndexingError: Too many indexers

### ISSUE THREAD

**Issue by kurucan** [JerBouma/FinanceToolkit#128]
some tickers gives an error on collect_all_ratios() function. 

Execution error
IndexingError: Too many indexers

example code is as below:
company = Toolkit(tickers=['DOM.L'], api_key=API_KEY, quarterly=True, sleep_timer=True, benchmark_ticker=None, progress_bar=False, start_date="2000-01-01")
company.ratios.collect_all_ratios()

**Comment by JerBouma** [comment]
Solved this issue, it should work in v1.8.5, let me know if it doesn't.
