### ISSUE TITLE
[FR] Adding calculation of resistance levels

### ISSUE THREAD

**Issue by rokdd** [JerBouma/FinanceToolkit#137]
**What's the problem of not having this feature?**
Do you have plans to add a calculation of resistance levels? Your toolkit is very complete and full featured but this would be nice to add.

**Describe the solution you would like**
A function to find the resistance levels

**Comment by JerBouma** [comment]
Could you add a source explaining what you mean with this? Definitely possible.

**Comment by rokdd** [comment]
Well I used in the past the following code: https://github.com/yongghongg/stock-screener/blob/main/stock_breakout_demo.ipynb and [his explanations ](https://medium.datadriveninvestor.com/how-to-detect-support-resistance-levels-and-breakout-using-python-f8b5dac42f21)to the code

**Comment by JerBouma** [comment]
I have introduced Support and Resistance levels based on local maxima and minima. Please have a look here: https://github.com/JerBouma/FinanceToolkit/blob/2119a21d3d9b726e8f4c20bd7e202fc7c441abe0/financetoolkit/technicals/technicals_controller.py#L3139-L3239

<img width="897" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/c3cd897a-2747-4b9d-9a33-73b0cff392f5">

**Comment by rokdd** [comment]
Works great, thank you!
