### ISSUE TITLE
[Bugs] small error in  get_interest_debt_per_share(..)

### ISSUE THREAD

**Issue by arbitrage-technology** [JerBouma/FinanceToolkit#138]
get_interest_debt_per_share(
    interest_expense: pd.Series,
    total_debt: pd.Series,
    shares_outstanding: pd.Series,
) -> pd.Series:
    
return (interest_expense / total_debt) * shares_outstanding

i think its return interest_expense /  shares_outstanding

**Comment by JerBouma** [comment]
What you are referring to is the interest per share ratio. The interest debt per share relates to how much interest a company pays on its debt relative to its shareholder base.

**Comment by arbitrage-technology** [comment]
thank you for your fast reply,

ok, sorry for the misunderstanding.
