### ISSUE TITLE
get_historical_data() method error

### ISSUE THREAD

**Issue by cianryan09** [JerBouma/FinanceToolkit#144]
I am running the following code:
```
# Simple example
companies = Toolkit(tickers=tickers, api_key=API_KEY, start_date=start_date, end_date=end_date) # this works fine

# retrieve the return data 
historical_data = companies.get_historical_data()
```

Which keeps throwing this error:
AttributeError: 'DataFrame' object has no attribute '_constructor_from_mgr'

It works on occasion but I frequently get the error more often than not.
Has anyone experienced the same issue? Is there a bug with the method?

**Comment by JerBouma** [comment]
Are you on the latest release (v1.9.1) and do you have your packages up-to-date to the requirements that are listed in https://github.com/JerBouma/FinanceToolkit/blob/main/pyproject.toml? 

This is usually due to outdated packages.

**Comment by cianryan09** [comment]
Thanks, I'm definitely using the latest release, 1.9.1. Pandas version is 2.2.2. I'm running it using google Colab so I need to pip install every time, which by default seems to install the required dependencies. Python version is 3.10.12

**Comment by cianryan09** [comment]
it worked after upgrading my colab package. I got it working in vs code but the Discovery module was not able to be imported. I will close the issue.
