### ISSUE TITLE
getting macroeconomic data

### ISSUE THREAD

**Issue by Nkhangwe** [JerBouma/FinanceToolkit#151]
while running this  "
from financetoolkit import Toolkit

toolkit = Toolkit(["AMZN", "ASML"])

cpi = toolkit.economics.get_consumer_price_index(period='yearly')

cpi.loc['2015':, ['United States', 'Netherlands', 'Japan']]" 

i keep on gettimg  the following error   "['Flag Codes'] not found in axis" what could be cause

**Comment by JerBouma** [comment]
It seems that OECD has changed their data structures which breaks a lot of the functionality from the Economy section. I don't have the capacity to work on this for the upcoming weeks unfortunately. Will let you know once I do have some time.

**Comment by Nkhangwe** [comment]
I explore the webpage i could find a way of obtain it? do you have a way maybe?

**Comment by JerBouma** [comment]
FMO unfortunately only has a small portion of the available options I offer. I need to re-evaluate this section of the Finance Toolkit.

I'll happily accept any PR that changes the code to FMP though!

**Comment by JerBouma** [comment]
Fixing everything as we speak! Expect new release today.

**Comment by JerBouma** [comment]
@Nkhangwe @NicoNicoNico123 

Just informing that most of the functionality works again in the newest release (v1.9.6). Unfortunately some datasets were archived by OECD (including the example you are calling thus this won't be available anymore for now).

I've considered FMP but given that OECD gives data from 70+ countries and FMP only 1, it makes little sense to switch over for now. I did reach out to them though.

<img width="933" alt="image" src="https://github.com/user-attachments/assets/f2f325a9-049b-4d6c-9ff5-0a0f907a891c">

**Comment by Nkhangwe** [comment]
Thank you

**Comment by NicoNicoNico123** [comment]
Thank for your contributions🙏🏻
