### ISSUE TITLE
[IMPROVE]

### ISSUE THREAD

**Issue by VNtechn** [JerBouma/FinanceToolkit#154]
Hello,**

I have tried to install financetoolkit but when i write this on a python program "from financetoolkit import Toolkit", python send me "TypeError". So, i have found that this error existed because i launched the program with python 3.8. 
Then, I installed python 3.11 and when I launch the program with python 3.11, python send me an error : "no module named 'financetoolkit' ", but when i tried to install financetoolkit with "pip install", it say to me that this module is already installed. I don't know where is the error ? Please help me (thanks).

**Comment by JerBouma** [comment]
This is related to your Python environment, e.g. from conda and has nothing to do with the package itself. Please verify your own settings.
