### ISSUE TITLE
[IMPROVE] Trailing Earnings Per Share calculation not correct?

### ISSUE THREAD

**Issue by mschaefer0815** [JerBouma/FinanceToolkit#156]
Hello,
first of all great tool!

I noticed a difference in the EPS when calculating the trailing=4 on quarterly data from FPM compared to the officially reported EPS from  SAP (SAP.DE)
Looking at the code for the get_earnings_per_share function I noticed that the trailing sum of the average shares is used for the calculation. (average_shares.T.rolling(trailing).sum().T). 

Since the Shares are reported as stock number I would have expected using the last number from the trailing window or a mean calculation over trailing window, but  not a sum.

Regards
Martin

**Comment by JerBouma** [comment]
Good catch, that is indeed an error. Feel free to create a PR that adjusts this or I'll do it probably somewhere in the next few weeks.

**Comment by mschaefer0815** [comment]
I did find some more and will do a PR later replaying sum with shares of current period.

Maybe you can have a look at the get_free_cash_flow_yield and get_book_value_per_share, there I am not so sure about the correct way to calculate trailing ratios. 
For get_book_value_per_share, dividing the sum of the book value by the sum of the shares is giving an average over the period, but technical i think it should be book value and shares of current period; same with market cap in fcf yield.

**Comment by JerBouma** [comment]
Issue fixed, I've adjusted the other ones as well as it is definitely false to group them in any way. Published a new release (v1.9.7) with these changes, thank you for the PR!
