### ISSUE TITLE
[IMPROVE]

### ISSUE THREAD

**Issue by Ecolacchi** [JerBouma/FinanceToolkit#158]
I have problem in download price for european equity. I receive this error message
No data could be retrieved for the risk free rate which results in calculations requiring an Excess Return to use a Risk Free Rate of 0.
No data found for the following tickers: UCG.MI
No data could be retrieved for the risk free rate which results in calculations requiring an Excess Return to use a Risk Free Rate of 0.
No data found for the following tickers: ISP.MI

**Comment by JerBouma** [comment]
Are you using a Free FMP plan? That is the reason given that the Free plan only supports U.S. tickers. Upgrade to a Premium plan to acquire this data.

**Comment by JerBouma** [comment]
@Ecolacchi 

Please update to v1.9.8 and your issue should be resolved (for historical data). For more information: https://github.com/JerBouma/FinanceToolkit/releases/tag/v1.9.8

![image](https://github.com/user-attachments/assets/e31d9825-f133-469d-80fe-01ed44dde73e)

**Comment by Ecolacchi** [comment]
Thank you Jerome, now works pefectly!!

*Dott. Ing. Emanuele Colacchi*
Mobile: +39 3209188383


algocapital.it 🚀
Canale Telegram <https://t.me/finanza_indipendente> 🆓
Analisi Tecnica con Python <https://amzn.to/3FUxb02> 💻
Python per il Trading <https://amzn.to/3Ar2XQS> 📈

          Value Investing <https://amzn.to/3RI7R6i> 🔥
Tasse ed Investimenti <https://amzn.to/3HbVzvD> 💰
Testi Consigliati <https://algocapital.it/libreria/> 📚



Il giorno dom 29 set 2024 alle ore 11:38 Jeroen Bouma <
***@***.***> ha scritto:
