### ISSUE TITLE
[IMPROVE] No data found for ISNS

### ISSUE THREAD

**Issue by rajesh-chawla** [JerBouma/FinanceToolkit#163]
**What's the feature that should be improved?**
Be able to recover programmatically if a ticker is not available.

**Describe how you would like the feature improved**
Provide a list of tickers that were not downloaded.

**Possibly describe the ideal way to improve this**
In addition to the 0 values in the return of get_historical_data(), please provide some way to identify if there is missing data for tickers. Alternatively, please clarify how by examining the return from get_historical_data(), I can deduce when a ticker is not providing data.

**Additional information**
Querying from FMP directly shows a valid quote, though in other places I'm seeing comments of the ticker being delisted.

https://[financialmodelingprep.com/api/v3/quote/ISNS?apikey=<snip>](https://financialmodelingprep.com/api/v3/quote/ISNS?apikey=<snip>)

A small repro:
```
tickers=['ISNS']
financeToolkit = Toolkit(tickers, 
                        api_key=API_KEY,
                        start_date='2022-12-01',
                        end_date='2024-01-01', 
                        benchmark_ticker="SPY")

fmp_data = financeToolkit.get_historical_data()
```
Returns:
```
Obtaining historical data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  9.38it/s]
No data found for the following tickers: ISNS
```

**Comment by JerBouma** [comment]
I do not quite understand the problem, this ticker seems to be delisted and the quote you receive is of many years ago. It also tells you explicitly for which ticker it was unable to acquire data and will do that for any collection of tickers.

What are you looking for exactly?

**Comment by rajesh-chawla** [comment]
Sorry for the noise -- I have what I need.
