### ISSUE TITLE
Class based approach

### ISSUE THREAD

**Issue by RajeshRk18** [JerBouma/FinanceToolkit#32]
Currently for every function, you need to pass api key as arguement which is not a sound approach. By looking into the code, I found that functions are classified as details, financial statements, and so on. Creating class for every component (details, financial_statements, ratios,..) will avoid us to pass api keys for every method / function and just need the instance of the class with api key as arguement. 

Example:
```Python
ratios = Ratios(api_key)
ratios.financial_ratios(ticker)
```

**Comment by JerBouma** [comment]
This is a great and logical approach indeed. As I currently do not have the time available to refractor the code, I'd like to invite you to look into this and create a PR.

**Comment by JerBouma** [comment]
I am currently working on an upgrade of the package. That will take some time but it will be class based!

**Comment by RajeshRk18** [comment]
Fine then!
