### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Fowfow** [JerBouma/FinanceToolkit#33]
Hi and thank you for your work,

In FundamentalAnalysis\fundamentalanalysis\financial_statements.py, in functions `income_statement(),` `balance_sheet_statement()` and `cash_flow_statement(),` the date column header in the returned dataframes should be a string (e.g. '2019') and not converted to integer (e.g. `int('2019'),` as done by `date = int( value['calendarYear'] )`.

This is to stay coherent with the dataframes returned by the functions implemented in FundamentalAnalysis\fundamentalanalysis\details.py, where the data column header is a string (e.g. '2019')

Best regards

**Comment by Fowfow** [comment]
Hi,

In FundamentalAnalysis\fundamentalanalysis\details.py, in function `discounted_cash_flow(),` we first try to fetch the data by calling 
`data_json = data[0]['historicalDCF'].`
If a keyError is raised because 'historicalDCF' doesn't exist, we retry again by calling 
`data_json = data[0].` 
This is where the error is, we should instead just call `data_json = data`. A test case is with the company ticker "BESI.AS".

Best regards

**Comment by JerBouma** [comment]
The package has been updated and should now work well.
