### ISSUE TITLE
problem when fetching DCF with certain companies

### ISSUE THREAD

**Issue by Fowfow** [JerBouma/FinanceToolkit#34]
Hi,

In FundamentalAnalysis\fundamentalanalysis\details.py, in function `discounted_cash_flow(),` we first try to fetch the data by calling 
`data_json = data[0]['historicalDCF'].`
If a keyError is raised because 'historicalDCF' doesn't exist, we retry again by calling 
`data_json = data[0].` 
This is where the error is, we should instead just call `data_json = data`.

A test case is with the company ticker "BESI.AS".

Best regards

**Comment by JerBouma** [comment]
The package has been updated, this is no longer relevant.
