### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by leejuncc** [JerBouma/FinanceToolkit#37]
I encountered the following error report, how to do:
'''
Traceback (most recent call last):
  File "fmp.py", line 2, in <module>
    from financetoolkit import Toolkit
  File "/Users/lijun/anaconda3/envs/test/lib/python3.8/site-packages/financetoolkit/__init__.py", line 5, in <module>
    from .base.toolkit_controller import Toolkit
  File "/Users/lijun/anaconda3/envs/test/lib/python3.8/site-packages/financetoolkit/base/toolkit_controller.py", line 7, in <module>
    from financetoolkit.base.models.fundamentals_model import (
  File "/Users/lijun/anaconda3/envs/test/lib/python3.8/site-packages/financetoolkit/base/models/fundamentals_model.py", line 15, in <module>
    tickers: str | list[str],
TypeError: 'type' object is not subscriptable
'''

conda list:
# Name                    Version                   Build  Channel
ca-certificates           2023.05.30           hecd8cb5_0  
financetoolkit            1.0.0                    pypi_0    pypi
libcxx                    14.0.6               h9765a3e_0  
libffi                    3.4.4                hecd8cb5_0  
ncurses                   6.4                  hcec6c5f_0  
numpy                     1.24.3                   pypi_0    pypi
openssl                   1.1.1t               hca72f7f_0  
pandas                    2.0.1                    pypi_0    pypi
pip                       23.0.1           py38hecd8cb5_0  
python                    3.8.16               h218abb5_3  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
readline                  8.2                  hca72f7f_0  
setuptools                67.8.0           py38hecd8cb5_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h6c40b1e_0  
tk                        8.6.12               h5d9f67b_0  
tzdata                    2023.3                   pypi_0    pypi
wheel                     0.38.4           py38hecd8cb5_0  
xz                        5.4.2                h6c40b1e_0  
zlib                      1.2.13               h4dc903c_0  

![20230609-212147](https://github.com/JerBouma/FinanceToolkit/assets/10191834/b24ef165-c209-47c8-b9ed-a932204d9926)

**Comment by JerBouma** [comment]
I am aware, will fix tomorrow!

**Comment by JerBouma** [comment]
This issue has been resolved. This is due to you being on an older version of Python. You are on 3.8 while the typing requirements are added in 3.10. I've made a temporary repository that will work (https://pypi.org/project/financetoolkit/1.0.2/) and it is made in such a way if you now will do `pip install financetoolkit -U` it will update to this version.

However, note that from now on, all future package versions will be based on Python 3.10 and onwards. I would recommend upgrading your Python distribution to get access to the newest features in due time.

```
(test_python38) jeroenbouma@Jeroens-MacBook-Pro FinanceToolkit % pip install financetoolkit 
Collecting financetoolkit
  Using cached financetoolkit-1.0.2-py2.py3-none-any.whl (42 kB)
Installing collected packages: financetoolkit
Successfully installed financetoolkit-1.0.2
(test_python38) jeroenbouma@Jeroens-MacBook-Pro FinanceToolkit % pip install pandas
Collecting pandas
  Using cached pandas-2.0.2-cp38-cp38-macosx_11_0_arm64.whl (10.7 MB)
Collecting pytz>=2020.1
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting numpy>=1.20.3
  Using cached numpy-1.24.3-cp38-cp38-macosx_11_0_arm64.whl (13.8 MB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, tzdata, six, numpy, python-dateutil, pandas
Successfully installed numpy-1.24.3 pandas-2.0.2 python-dateutil-2.8.2 pytz-2023.3 six-1.16.0 tzdata-2023.3
(test_python38) jeroenbouma@Jeroens-MacBook-Pro FinanceToolkit % python
Python 3.8.16 (default, Mar  1 2023, 21:18:45) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from financetoolkit import Toolkit
>>> Toolkit(['AAPL', 'TSLA'], 'API_KEY').get_balance_sheet_statement()
<stdin>:1: DeprecationWarning: This version of the Finance Toolkit is depreciated. Finance Toolkit 1.0.3 and onwards require Python 3.10 and higher. Please update to the latest version of Python and the Finance Toolkit.
date                                         2018          2019         2020          2021          2022
AAPL Cash and Cash Equivalents        25913000000   48844000000  38016000000   34940000000   23646000000
     Short Term Investments           40388000000   51713000000  52927000000   27699000000   24658000000
     Cash and Short Term Investments  66301000000  100557000000  90943000000   62639000000   48304000000
     Accounts Receivable              48995000000   45804000000  37445000000   51506000000   60932000000
     Inventory                         3956000000    4106000000   4061000000    6580000000    4946000000
...                                           ...           ...          ...           ...           ...
TSLA Minority Interest                 1390361000    1492000000   1454000000    1394000000    1194000000
     Total Liabilities and Equity     29739614000   34309000000  52148000000   62131000000   82338000000
     Total Investments                          0             0            0     131000000    5932000000
     Total Debt                       13827271000   13419000000  11739000000    6834000000    3099000000
     Net Debt                         10141653000    7151000000  -7645000000  -10742000000  -19086000000

[86 rows x 5 columns]
>>> exit()
(test_python38) jeroenbouma@Jeroens-MacBook-Pro FinanceToolkit % conda list
# packages in environment at /Users/jeroenbouma/miniconda3/envs/test_python38:
#
# Name                    Version                   Build  Channel
ca-certificates           2023.05.30           hca03da5_0  
financetoolkit            1.0.2                    pypi_0    pypi
libcxx                    14.0.6               h848a8c0_0  
libffi                    3.4.4                hca03da5_0  
ncurses                   6.4                  h313beb8_0  
numpy                     1.24.3                   pypi_0    pypi
openssl                   1.1.1t               h1a28f6b_0  
pandas                    2.0.2                    pypi_0    pypi
pip                       23.0.1           py38hca03da5_0  
python                    3.8.16               hc0d8a6c_3  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
setuptools                67.8.0           py38hca03da5_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h80987f9_0  
tk                        8.6.12               hb8d0fd4_0  
tzdata                    2023.3                   pypi_0    pypi
wheel                     0.38.4           py38hca03da5_0  
xz                        5.4.2                h80987f9_0  
zlib                      1.2.13               h5a0b063_0  
(test_python38) jeroenbouma@Jeroens-MacBook-Pro FinanceToolkit % 
```
