### ISSUE TITLE
[BUG] Financial Ratios - Zero Division Error

### ISSUE THREAD

**Issue by ptyson17** [JerBouma/FinanceToolkit#39]
I encountered a "Zero Division Error" when seeking financial ratios for a particular company.

The company in question was 'TNE.AX' - Technology One (ASX company). I have checked my FMP API and it now works (e.g. the income statement populates correctly).

I plugged the error into Chat GPT (of course) and it came back saying that this could happen when COGS wasn't provided - which is perhaps true. As an ASX listed company, TNE.AX's financial information may not tranfer across into FMP 100% accurately.

In any case, Chat GPT suggests an alteration to the profitability.py file. Have attached its suggestion - I'm still very new to this so will leave in your capable hands!

[ZeroDivisionError.txt](https://github.com/JerBouma/FinanceToolkit/files/12028786/ZeroDivisionError.txt)
[Chat GPT Suggestion.docx](https://github.com/JerBouma/FinanceToolkit/files/12028806/Chat.GPT.Suggestion.docx)

**Comment by Vik2009** [comment]
I confirm this issue.

**Comment by JerBouma** [comment]
Working on fixing this, so far some good progress. It required a bit more effort than simply excluding division by zero. I'll see if I can merge this in later this week.

<img width="1449" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/33b74904-23c8-4ff3-9986-2bc5f4a331e0">

**Comment by ptyson17** [comment]
great, thanks Jeroen. Yes I did need to get a Premium key, but being based in Australia I understand data for our market is less readily available.
