### ISSUE TITLE
[IMPROVE] .get_historical_ratios() HTTP error 404 on invalid tickers

### ISSUE THREAD

**Issue by sword134** [JerBouma/FinanceToolkit#42]
In the current version calling .get_historical_ratios() or collect_all_ratios() on a list of symbols in which 1 ticker is invalid (delisted or otherwise not on yahoo finance) will result in the following error: urllib.error.HTTPError: HTTP Error 404: Not Found

The solution is to add an except to catch these tickers. Ideally they should be removed from the symbol list so as to not pollute the dataset. Perhaps a boolean for the user in Toolkit() to determine if the script should automatically drop or keep "corrupt" symbols.

**Comment by JerBouma** [comment]
Working on this!

**Comment by sword134** [comment]
I've made a pull request to fix the specified issue.

**Comment by JerBouma** [comment]
This issue has been resolved as you can see tickers are automatically taken out. This required more than just the historical data to change but all functionality.

<img width="1136" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/efcec189-2d10-4cc9-a3fd-0bfb587a9bbc">
