### ISSUE TITLE
How to resume a download?

### ISSUE THREAD

**Issue by Thomas-Frew** [JerBouma/FinanceToolkit#68]
Hello everyone!

I don't have the most stable network connection, and I was wondering if it was possible to resume a data download for a large dataset if the connection is interrupted.

If not, do you have any tips to minimise losses (like downloading in stages or creating some sort of checkpoint system?)

Thanks!

**Comment by JerBouma** [comment]
Hi @Thomas-Frew,

The Toolkit class gives you the ability to provide a "custom" dataset for both historical as well as fundamental data. So as an example you can do the following:

```python
from financetoolkit import Toolkit
import pandas as pd

ticker_list = ['AMZN', 'AAPL', 'TSLA', 'MU', 'GOOG', 'TSM']

# Only picking the first three as an example
companies = Toolkit(tickers=ticker_list[:2], api_key="API_KEY")

# Load historical data and save to a variable
historical_data = companies.get_historical_data()

# Write to Pickle
historical_data.to_pickle("saved_stocks.pickle")

# Load the Pickle (in the case your current instance is erased)
loaded_data = pd.read_pickle('saved_stocks.pickle')

# Reinitialise the Toolkit with the historical data
companies_2 = Toolkit(tickers=ticker_list[:2], api_key="API_KEY", historical=loaded_data)

# Show bollinger bands as an illustration of the capability
companies_2.technicals.get_bollinger_bands()
```

This gets you the following without the requirement to download any of the data again:

<img width="702" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/e0b37ab7-5ac8-46be-bae9-6584efac0802">

Therefore, if you create a loop over your tickers, write to pickle and when you got everything combine the pickles, you get what you are looking for. As an example:

<img width="1126" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/02986a10-0e5d-4817-a88c-2e92fcdcffd2">

Working with custom datasets is a little bit experimental however. I believe it works in pretty much every area but feel free to let me know if you run into issues.

**Comment by JerBouma** [comment]
Hi @Thomas-Frew, did this fix your problem?

**Comment by Thomas-Frew** [comment]
Thanks for your help! This was very useful.
