### ISSUE TITLE
[IMPROVE] Please remove the unused dependency 'financedatabase'

### ISSUE THREAD

**Issue by yurivict** [JerBouma/FinanceToolkit#78]
[here](https://github.com/JerBouma/FinanceToolkit/blob/main/pyproject.toml#L44)

It is never imported.
On the other hand, financedatabase uses FinanceToolkit, so that the dependency goes the other way.

**Comment by JerBouma** [comment]
I originally planned to add functionality from the FinanceDatabase into the FinanceToolkit. I'll take this dependency out in the next release, is it causing issues for you?

**Comment by yurivict** [comment]
> [...] is it causing issues for you?

Yes, this creates a circular dependency. Circular dependencies are allowed between Python packages, but I need to create corresponding FreeBSD ports, and circular dependencies aren't allowed for ports.

**Comment by JerBouma** [comment]
For the time being you could use: `pip install financetoolkit --no-dependencies` or alternatively download the repository, take out the financedatabase from the pyproject.toml and use `python -m build` then use that `.whl` file. I'll adjust the package later this week most likely.

Any idea how I could get around this restriction in due time? E.g. it could very well be that at some point I do want to introduce the FinanceDatabase as a dependency again. How could I make it work for you in that case?

**Comment by yurivict** [comment]
> [...] How could I make it work for you in that case?

If two packages need to use each other - they can't be installed separately. They should really be merged, because they become one unit.

I only encountered this once before. When packages insist on being separate - we just need to patch one of them to break the cycle, and then whenever one of them is required somewhere else - we need to remember to always add both. This would be error-prone, because this is easy to forget.

Allowing circular dependencies is one of the weaknesses of the Python technology.
C++ projects don't and can't have such problem.

**Comment by JerBouma** [comment]
The two packages can be an addition to each other but don't really need each other. I think for the time being it makes sense to not include the financedatabase. In any case, I got you covered, please update to v1.6.1 that should do the trick.

**Comment by yurivict** [comment]
Thank you!

**Comment by JerBouma** [comment]
I assume this issue is now resolved. If it isn't, please let me know.
