### ISSUE TITLE
Significant time delays in get_historical_data()

### ISSUE THREAD

**Issue by cianryan09** [JerBouma/FinanceToolkit#80]
Hi,

I am having significant speed issues when running the get_historical_data() function.
The Toolkit works fine but running the above even for three stocks, takes ~135 seconds. Running for 100 takes 200 seconds. If I run for a large amount of stocks (say the 9500 or so of the large, mid and small cap stocks in the financedatabase module) the code always crashes and I get a long list of exception errors in multiple threads.

I ran CProfile, and no specific line of code seems to cause the backlog (tottime all < 0.001).

Does anyone have any idea on how to what could be the cause of this and stop errors from occurring when running for large numbers of stocks? Code snippet below:

`companies = Toolkit(
    tickers=ticker_list,
    start_date = date,
    api_key="xxxxxx",
)

hist_data = companies.get_historical_data()`

**Comment by JerBouma** [comment]
What FinancialModelingPrep are you on? I've built in a wait timer when you reach your rate limit per minute. E.g. the Starter plan has a limit of 250 per minute. Most likely you've hit that and then when you try to run for a few companies straight after it waits again.

To overcome this, you'd have to upgrade your plan sadly. If this doesn't seem to be the issue please let me know and provide all the errors you get!

**Comment by JerBouma** [comment]
Hi @cianryan09, this issue should now be resolved with the release of v1.6.1 which will automatically disable the wait timer that you are having issues with in this case. See: https://github.com/JerBouma/FinanceToolkit/releases/tag/v1.6.3

Please let me know if this _doesn't_ solve the issue.

**Comment by cianryan09** [comment]
Thank you Jeroen for the reply and apologies for the delay in getting back to your original response. I am currently on the free plan just to see what it's like. Does 1 stock = 1 call to the API or do all stocks in the 'tickers' variable count as one call? E.g. if I have 250 tickers in the ticker list and run Toolkit, does that exhaust my calls for the day?

I also updated to 1.6.3 and it did not seem to result in any speed improvements but that may just be purely due to the call limits described above.

**Comment by JerBouma** [comment]
Let's say you input TSLA, AAPL and MSFT into the Toolkit. Every time you call a function that collects data, it will costs about 3 API calls. So for balance sheets, income statements, cash flow statements, historical data and more. So for example if you call Balance + Income + Cash Flow that's 9 API calls.

I don't fully understand how it takes so long for you to collect data as it should be almost instantly. For example I am using a Free key here and it takes less than 3 seconds. Could you elaborate further?

<img width="1152" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/724ef7b0-5854-4f25-b519-0ee98ba1aa08">

**Comment by cianryan09** [comment]
good to know, thanks. This is the code I have run and I timed it:
![image](https://github.com/JerBouma/FinanceToolkit/assets/74511315/7169664a-bb3a-4279-be38-fee1659c8bc1)
![image](https://github.com/JerBouma/FinanceToolkit/assets/74511315/e229bfa3-7312-4f56-98f1-2febf1c0597e)
(date is jut today's date five years ago)
so the same three stocks is taking me nearly 9 seconds. Is it possibly to do with how my environment is set up?
![image](https://github.com/JerBouma/FinanceToolkit/assets/74511315/3f631064-add0-47e0-9adb-f6a8d68c8385)

Not really a coding expert here so excuse me if the question is basic or off-topic.

**Comment by JerBouma** [comment]
Does it change anything if you define the `start_time` right before the `hist_data`? I can't imagine it being that long. The environment you are using is fine, it shouldn't be an issue there.

The API limit should not be an issue as I've made sure that once you hit the limit it will just tell you no data could be collected instead of giving you errors or letting you wait.

**Comment by cianryan09** [comment]
I tried the above but it made almost no difference. I also upgraded to one of the paid plans and still no speed improvement. And its nothing else in my script causing the slowdown - if I comment out the `.get_historical()` line it drops to 2 seconds
It's hardly a hardware issue? Maybe all the threading uses a lot of memory/CPU that my older equipment can't handle?

**Comment by JerBouma** [comment]
Hi! I am expecting this to be a hardware issue. What you can try is using Google Colab which already cuts it down to 5 seconds. For other components this can be as little as 2-3 seconds in Google Colab.

<img width="1512" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/6aa15d41-ec1d-41fa-b429-7786ed5c3ca1">

**Comment by cianryan09** [comment]
Hi - using Colab does cut the time down by a lot. 1000 tickers takes around 2 minutes. Thank you for the suggestion!
