### ISSUE TITLE
[IMPROVE] Documentation search bar

### ISSUE THREAD

**Issue by giraffeingreen** [JerBouma/FinanceToolkit#89]
**What's the feature that should be improved?**
You have really nice documentation, is there an easy way to add a search bar?

**Comment by JerBouma** [comment]
Thank you, I am going to look into this! Should definitely be possible.

**Comment by JerBouma** [comment]
Search bar is in! 🫡

https://www.jeroenbouma.com/projects/financetoolkit/docs

<img width="1390" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/35950580-e644-4939-b7d0-6ba6e1f759bc">
