### ISSUE TITLE
[IMPROVE]List of all the available names that can be used in a custom ratio

### ISSUE THREAD

**Issue by giraffeingreen** [JerBouma/FinanceToolkit#90]
**What's the feature that should be improved?**

All the valid names that can be used in a custom ratio.

**Describe how you would like the feature improved**
Include a list of all the valid names that can be used in a custom ratio.

**Possibly describe the ideal way to improve this**
Using pandas should be easy to get the column names.

**Additional information**
At this point in the code you already have all the data available.
https://github.com/JerBouma/FinanceToolkit/blob/82550930d55bd0f63611e7750201735edaaab692/financetoolkit/ratios/ratios_controller.py#L299

**Comment by JerBouma** [comment]
Are you feeding the custom ratios into the Toolkit initialization or directly in the custom ratios function? I can indeed quite easily add it in for the latter!

**Comment by JerBouma** [comment]
Will do a release early this year with this functionality, already have it available on the develop branch.

<img width="1170" alt="image" src="https://github.com/JerBouma/FinanceToolkit/assets/46355364/1f61ba3c-ec56-41f9-b9e1-b7e66588e4a1">

**Comment by giraffeingreen** [comment]
That's exactly what I was excepting! Thank you!

**Comment by JerBouma** [comment]
Fixed in v1.7.3 👍 

https://github.com/JerBouma/FinanceToolkit/releases/tag/v1.7.3
