### ISSUE TITLE
[IMPROVE] piotroski stock criteria

### ISSUE THREAD

**Issue by wlemmon** [JerBouma/FinanceToolkit#91]
this seems backward

(https://github.com/JerBouma/FinanceToolkit/blob/b39fa9e111d464a6bff645c0e84eda1bea541baf/financetoolkit/models/piotroski_model.py#L278)

**Comment by JerBouma** [comment]
Care to elaborate?

**Comment by wlemmon** [comment]
my mistake, apologies :D i misread the "did not issue common equity" part of the original paper.
